controller_manager:
  ros__parameters:
    update_rate: 100
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    shoulder_yaw_joint_controller:
      type: position_controllers/JointGroupPositionController
    shoulder_pitch_joint_controller:
      type: position_controllers/JointGroupPositionController
    elbow_joint_controller:
      type: position_controllers/JointGroupPositionController
    wrist_roll_joint_controller:
      type: position_controllers/JointGroupPositionController
    wrist_pitch_joint_controller:
      type: position_controllers/JointGroupPositionController
    left_finger_joint_controller:
      type: position_controllers/JointGroupPositionController
    right_finger_joint_controller:
      type: position_controllers/JointGroupPositionController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.4
    wheel_radius: 0.1
    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    publish_limited_velocity: false

shoulder_yaw_joint_controller:
  ros__parameters:
    joints:
      - shoulder_yaw_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

shoulder_pitch_joint_controller:
  ros__parameters:
    joints:
      - shoulder_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

elbow_joint_controller:
  ros__parameters:
    joints:
      - elbow_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

wrist_roll_joint_controller:
  ros__parameters:
    joints:
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

wrist_pitch_joint_controller:
  ros__parameters:
    joints:
      - wrist_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_finger_joint_controller:
  ros__parameters:
    joints:
      - left_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_finger_joint_controller:
  ros__parameters:
    joints:
      - right_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
